
cors:
  originPatterns: https://localhost:8080,https://localhost:8081
spring:
  server: 8888
  application:
    name: projeto-erudio
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show-sql: true
          format-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/projeto-erudio
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'
logging:
  level:
    br.com.erudio: DEBUG



