
cors:
  originPatterns: https://localhost:8080,https://localhost:8081
file:
  upload-dir: /Users/miche/Downloads/file
security:
  jwt:
    token:
      secret-key: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
      expire-length: 3600000
  upload-dir: /Users/miche/Downloads/file
email:
  subject: "Defaut subject"
  message: "Defaut message"
spring:
  server: 8888
  application:
    name: projeto-erudio
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          show-sql: true
          format-sql: true
    open-in-view: false
  servlet:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password:  ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: jdbc:postgresql://localhost:5433/projeto-erudio
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'
logging:
  level:
    br.com.erudio: DEBUG



