name: Continuous Integration and Delivery with GitHub Action

on:
  push:
    branches:
      - "main"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Setup Java 21
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
    - name: Build Application .jar
      working-directory: ./Users/miche/git/projeto-erudio
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./Users/miche/git/projeto-erudio
      run: docker compose build

    - name:  Push to Docker Hub Container Registry
      run:
          docker tag ${{ secrets.DOCKER_USER }}/projeto-erudio:latest ${{ secrets.DOCKER_USER }}/projeto-erudio:${{github.run_id}}
        
          docker push ${{ secrets.DOCKER_USER }}/projeto-erudio:latest
          docker push ${{ secrets.DOCKER_USER }}/projeto-erudio:${{github.run_id}}
